### ISSUE TITLE
Client credentials grant type support

### ISSUE THREAD

**Issue by hafizh** [zalando/planb-provider#119] opened 2016-05-02 12:26 UTC
In Fashion store apps we have a use case similar to a guest user. Without authentication, user can use the functionality that doesn’t have any customer resource data or any personalisation features. Such functionality includes plain catalog navigation, inspiration content or generic my feed, etc. To support such a use case, it would make sense for us to have the support for client credentials flow as stated in the [spec](https://tools.ietf.org/html/rfc6749#section-4.4). 

An alternative could be to create a default guest-like user and get an access token through a Resource owner password credentials flow using that user. But, this is more a workaround and doesn’t seem to add any value.

**Comment by danieldelhoyo** [comment] 2016-05-03 09:45
This is a duplicate of #66

**Closed** 2016-05-04 09:18 UTC
Labels: duplicate
